name: Python CI

on:
    push:
    pull_request:

jobs:
    build:
        name: Build on ${{ matrix.os }} - Python ${{ matrix.python-version }}
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                python-version: [3.8, 3.9, 3.10]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install flake8 pytest

            - name: Run linter (flake8)
              run: flake8 .

            - name: Run script
              run: python script.py

            - name: Run tests with pytest and save result
              run: |
                  pytest > result.log || true

            - name: Upload result.log artifact
              uses: actions/upload-artifact@v3
              with:
                  name: test-log-${{ matrix.os }}-py${{ matrix.python-version }}
                  path: result.log
